---
- name: fail when node user is not defined
  fail: msg="The node_user variable must be set."
  when: (node_user is not defined) or (not node_user)

# set facts to reliably determine node variables
- name: discover node
  include_tasks: discover/node.yml

# load per-os and per distro variables
- name: load ubuntu variables
  include_vars: ubuntu.yml
  when: is_ubuntu_derivative

- name: load redhat variables
  include_vars: redhat.yml
  when: is_redhat_derivative

  # refresh cache on ubuntu
- name: refresh apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: is_ubuntu_derivative
  become: true

# install build dependencies
- name: install git
  package: name=git state=present
  become: true

# install nodenv
- name: install nodenv
  include_tasks: nodenv.yml

# install node
- name: install node
  include_tasks: node.yml
